apiVersion: v1
kind: Service
metadata:
  name: odoo-shop
  namespace: odoo
  labels:
    apps: odoo-shop
spec:
  type: NodePort
  ports:
  - port: 8069
    targetPort: odoo
  selector:
    app: odoo-shop
    tier: frontend
    