apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: odoo-db
  namespace: odoo

spec: 
  replicas: 1
  template:
    metadata:
      labels:
        appdb: odoo-db
    spec: 
      containers:
      - image: postgres:9.6-alpine
        name: odoo-db 
        env:
        - name: POSTGRES_USER
          value: odoo
        - name: POSTGRES_PASSWORD
          value: odoodbpassword
        - name: PGDATA
          value: /var/lib/postgresql/data/pgdata
        ports:
        - containerPort: 5432
          name: odoo-db
        