apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: odoo-shop
  namespace: odoo
spec: 
  replicas: 1
  template:
    metadata:
      labels:
        app: odoo-shop
    spec:
      containers:
        - image: odoo:latest
          name: odoo
          env:
          - name: db
            value: odoo-db
          - name: USER
            value: odoo
          - name: PASSWORD
            value: odoodbpassword
          ports:
          - containerPort: 8069
            name: odoo        