apiVersion: v1
kind: Service
metadata:
  name: odoo-db
  namespace: odoo
  labels:
    app: odoo-shop
spec:
  ports:
  - port: 5432
  - tier: backend
  
  selector:
    app:odoo-shop
    ##type: NodePort

  