---
kind: Namespace
apiVersion: v1
metadata:
  name: odoo
  labels:
    name: odoo
---
apiVersion: v1
kind: Service
metadata:
  name: odoo-db-svc
  namespace: odoo
spec:
  ports:
  - port: 5432

  selector:
    appdb: odoo-db
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: odoo-db
  namespace: odoo
spec: 
  replicas: 1
  template:
    metadata:
      labels:
        appdb: odoo-db
    spec: 
      containers:
      - name: odoo-db
        image: postgres:9.6-alpine
        env:
        - name: POSTGRES_USER
          value: odoo
        - name: POSTGRES_PASSWORD
          value: password
        - name: PGDATA
          value: /var/lib/postgresql/data/pgdata
        ports:
        - containerPort: 5432
---

apiVersion: v1
kind: Service
metadata:
  name: odoo-shop-svc
  namespace: odoo
spec:
  type: NodePort
  ports:
  - port: 8069
    targetPort: web-port

  selector:
    app: odoo-shop
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: odoo-shop
  namespace: odoo
spec: 
  replicas: 1
  template:
    metadata:
      labels:
        app: odoo-shop
    spec:
      containers:
      - name: odoo-shop
        image: odoo:latest
        env:
        - name: HOST
          value: odoo-db-svc
        - name: USER
          value: odoo
        - name: PASSWORD
          value: password
        securityContext:
          privileged: true
          runAsUser: 0
        ports:
          - containerPort: 8069
            name: web-port
         


            
